# Generated by Django 3.2 on 2021-04-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
